(function () {
  const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const money = n => '$' + Math.round(Number(n) || 0).toLocaleString();
  const estimates = [['B4 Warehouse Mezzanine & Lab',2313182,1056.25],['B4 Warehouse Mezzanine & Lab · Budget',2480000,1132.40],['B4 Warehouse Mezzanine & Lab · GMP',2270000,1037.85]];
  const estimateRows = [
    ['Temporary Toilet Trailer Mob./Demob.','Temporary Sanitary Facilities','Jobsite Management','Z - General','Bid Package',4000],['Temporary Toilets Monthly Rental','Temporary Sanitary Facilities','Jobsite Management','Z - General','Bid Package',23000],['Final Cleaning','Final Cleaning - Interiors','Jobsite Management','Z - General','Bid Package',3285],['Demo Slab on Grade at New Footing','Selective Site and Building Demolition','Demolition','F - Special Construction and Demolition','Bid Package',6830],['Concrete Spread Footing','Cast-In-Place Concrete (Turnkey)','Foundations','A - Substructure','Bid Package',16830],['Mezzanine Posts & Rail, D/B Stair','Miscellaneous Metal Fabrications','Superstructure','B - Shell','Bid Package',90957],['Roofing Patch - Misc Repair','Roofing','Exterior Skin','B - Shell','Bid Package',22432],['Interior Framing & Drywall','Drywall and Framing','Interior Construction','C - Interiors','Bid Package',159494],['VRC Series D Material Lift','Dumbwaiters','Electrical','D - Services','Bid Package',159363],['Fire Sprinkler Adjustments','Fire Suppression','Fire Protection','D - Services','Bid Package',42000],['Lab Sink Fixtures, Piping & Rough-In','Plumbing','Plumbing','D - Services','Bid Package',121977],['Mechanical System','HVAC','HVAC','D - Services','Bid Package',187472],['Lighting, Branch & Equipment Power','Electrical','Electrical','D - Services','Bid Package',373880]
  ].map((r,i)=>({id:i,sov:r[0],description:r[1],values:{System:r[2],UF1:r[3],UF2:r[3],UF3:r[3],UF4:r[3],MF1:r[4],MF2:r[4],MF3:r[4],'Bid Package':r[4],'Job Cost Phase':r[1]},budget:r[5]}));
  const workbookRows=[['015219.1200','Temporary Toilet Trailer Mob./Demob.',4000],['015219.1200','Temporary Toilets Monthly Rental',23000],['010000.9816','Monthly Rental',1716],['010000.9817','Plywood Enclosure',2220],['010000.9815','Scaffold Stair for Safe Access',12057],['010000.9840','Final Cleaning',3285],['020000.0245','Demo Slab on Grade at New Footing',6830],['024119.9950','Scanning / Utility Locating',3498],['028000.1100','Hazardous Materials Survey',3500],['033000.1150','Concrete Spread Footing',16830],['033000.9900','Excavate Spread Footing',3440],['033000.9900','Soil Testing for Off-Haul',3585],['030000.1320','CONC-1,2 & Rubber Base',27250],['055000.9900','Mezzanine Posts & Rail, D/B Stair',90957],['061000.3340','Roof Joists & Leveling Curbs',36263],['075113.7100','Roofing Patch - Misc Repair',22432],['080000.0805','Hollow Metal DFH with 1/4" Glass',26669],['090000.0920','Interior Framing & Drywall',159494],['090000.0950','ACT 2x2 Square USG Olympia in 9/16" Grid',39040],['090000.0990','Interior Paint',22320],['140000.1410','VRC Series D Material Lift',159363],['210000.0000','Fire Sprinkler Adjustments',42000],['210000.0001','Relocate (E) Piping Allowance',5000],['220000.1008','Lab Sink Fixtures, Piping & Rough-In',121977],['226213.C110','CDA, Argon, O2 Systems',85710],['230000.1100','Mechanical System',187472],['260002.1050','Lighting, Branch & Equipment Power',373880],['270000.1010','Low Voltage Cabling & Terminations',37500],['013150.3610','Estimating Assistant (Precon)',1380],['013150.3110','Estimator/Project Buy-out (Precon)',7680],['013150.1310','Project Manager (Precon)',7400],['010000.2100','Jobsite Management',417068],['017413.2100','Interim Clean Up & Safety Labor',87500],['010000.3100','Project Requirements',46839]];
  estimateRows.length=0;workbookRows.forEach((r,i)=>{const key=r[0].slice(0,2);const map={ '01':['Jobsite Management','Z - General','Z10 - General Requirements','Z1050 - Temporary Facilities and Controls','01 00 00 - General Requirements','01 52 00 - Construction Facilities','01.25 - Temporary Facilities'], '02':['Demolition','F - Special Construction and Demolition','F30 - Demolition','F3030 - Selective Demolition','02 00 00 - Existing Conditions','02 41 00 - Demolition','02.45 - Demolition'], '03':['Foundations','A - Substructure','A10 - Foundations','A1010 - Standard Foundations','03 00 00 - Concrete','03 30 00 - Cast-in-Place Concrete','03.30 - Concrete'], '05':['Superstructure','B - Shell','B10 - Superstructure','B1015','05 00 00 - Metals','05 50 00 - Metal Fabrications','05.50 - Metal Fabrications'], '06':['Exterior Skin','B - Shell','B30 - Exterior Horizontal Enclosures','B3010 - Roofing','06 00 00 - Wood, Plastics, and Composites','06 10 00 - Rough Carpentry','06.10 - Rough Carpentry'], '07':['Exterior Skin','B - Shell','B30 - Exterior Horizontal Enclosures','B3010 - Roofing','07 00 00 - Thermal and Moisture Protection','07 51 00 - Built-Up Roofing','07.50 - Roofing'], '08':['Interior Construction','C - Interiors','C10 - Interior Construction','C1030 - Interior Doors','08 00 00 - Openings','08 00 00 - Openings','08.10 - Doors and Frames'], '09':['Interior Construction','C - Interiors','C10 - Interior Construction','C1010 - Interior Partitions','09 00 00 - Finishes','09 00 00 - Finishes','09.21 - Finishes'], '14':['Electrical','D - Services','D10 - Conveying','D1010 - Conveying','14 00 00 - Conveying Equipment','14 00 00 - Conveying Equipment','14.10 - Dumbwaiters'], '21':['Fire Protection','D - Services','D40 - Fire Protection','D4010 - Fire Suppression','21 00 00 - Fire Suppression','21 00 00 - Fire Suppression','21.00 - Fire Suppression'], '22':['Plumbing','D - Services','D20 - Plumbing','D2000 - Plumbing','22 00 00 - Plumbing','22 00 00 - Plumbing','22.00 - Plumbing'], '23':['HVAC','D - Services','D30 - HVAC','D3000 - HVAC','23 00 00 - HVAC','23 00 00 - HVAC','23.00 - HVAC'], '26':['Electrical','D - Services','D50 - Electrical','D5000 - Electrical','26 00 00 - Electrical','26 00 00 - Electrical','26.00 - Electrical'], '27':['Conveying Systems','D - Services','D60 - Communications','D6000 - Communications','27 00 00 - Communications','27 00 00 - Communications','27.10 - Structured Cabling']};const v=map[key]||['Jobsite Management','Z - General','Z10 - General Requirements','Z1020 - Administrative Requirements','01 00 00 - General Requirements','01 00 00 - General Requirements','99.15 - Project Requirements'];estimateRows.push({id:i,order:r[0],sov:r[0],description:r[1],lineDescription:r[1],budget:Number(r[2]),values:{System:v[0],UF1:v[1],UF2:v[2],UF3:v[3],UF4:v[3],MF1:v[4],MF2:v[5],MF3:v[5],'Bid Package':v[6],'Job Cost Phase':v[2]}});});
  estimateRows.forEach(r=>{r.values['Use Groups']=r.values.System;r.values.Building='02 Pediatric Hospital';});
  let estimateGroups=['System','UF1','Bid Package'], estimateOpen={}, source='Connect to Estimate', manualLevels=2, nextId=5;
  let manualRows=[{id:'m1',parent:null,level:1,sov:'General Conditions',description:'',budget:0},{id:'m2',parent:'m1',level:2,sov:'Site management',description:'',budget:0},{id:'m3',parent:null,level:1,sov:'Structure',description:'',budget:0},{id:'m4',parent:'m3',level:2,sov:'Concrete frame',description:'',budget:0}];
  const groups=['System','Use Groups','Building','UF1','UF2','UF3','UF4','MF1','MF2','MF3','Bid Package','Job Cost Phase'];
  const opts=(items,selected)=>items.map(v=>'<option '+(v===selected?'selected':'')+'>'+esc(v)+'</option>').join('');
  document.body.innerHTML='<div class="topbar"><b>▦</b><b>▣ Projects</b><span>▤ Enterprise Workspace</span></div><div class="projectbar"><span class="logo">HUB</span><span>›</span><strong>D0-A25061-00 - SHOCKWAVE - 2026 MISC PROJECTS</strong><span>›</span><strong>CASHFLOW FORECASTING</strong></div><div class="shell"><aside><a class="back" href="index.html">← Back to Home</a><h3>Cashflow lifecycle</h3>'+[['index.html','Lifecycle Overview','▣'],['prediction.html','Early Cashflow Prediction','◈'],['manual-forecast.html','Manual Forecast Setup','＋'],['wbs.html','Work Breakdown Structure Setup','⌘'],['bill-code.html','Bill Code Setup','⌗'],['billing.html','Estimate Billing Structure','＋'],['forecast.html','Cashflow Forecast Grid','▤']].map(n=>'<a href="'+n[0]+'" class="'+(n[1]==='Bill Code Setup'?'active':'')+'"><span class="phase"><i>'+n[2]+'</i>'+n[1]+'</span></a>').join('')+'<h3>Workspace</h3><a href="modules/reports.html">▧ Reports</a><a href="modules/settings.html">⚙ Project Settings</a></aside><main class="main"><div class="source-strip"><span class="connected">✓ Cosential · connected</span><span class="connected">✓ Ediphi · connected</span><span class="connected">✓ P6 · connected</span></div><div id="content"></div></main></div>';
  const content=document.getElementById('content');
  const saveBillCode=(kind,rows,levels,selectedGroups)=>localStorage.setItem('hubBillCodeStructure',JSON.stringify({source:kind,levels,groups:selectedGroups||[],rows}));
  function manualTable(){return manualRows.map(r=>'<tr class="'+(r.level>1?'child-row':'parent-row')+'" data-mrow="'+r.id+'"><td><span class="manual-indent">'+(r.level>1?'↳':'')+'</span><input data-mf="sov" value="'+esc(r.sov)+'" placeholder="SOV item *"></td><td><input data-mf="description" value="'+esc(r.description)+'" placeholder="Description (optional)"></td><td><input data-mf="budget" type="number" min="0" value="'+Number(r.budget||0)+'" placeholder="0"></td><td>'+ (r.level<manualLevels?'<button class="btn add-sub" data-parent="'+r.id+'">＋ Add subitem</button>':'') +'<button class="row-delete" data-mdelete="'+r.id+'">×</button></td></tr>').join('');}
  function renderManual(){
    content.innerHTML='<section class="section"><div class="head"><div><p class="eyebrow">Bill Code Setup · Shockwave</p><h2>Build a bill code structure</h2><p class="copy">Create a one-, two-, or three-level hierarchy for the project cashflow forecast.</p></div><span class="status">Unsaved changes</span></div><div class="body"><div class="bill-toolbar-manual"><label>Bill Code Structure Name<input value="Owner Bill Structure" placeholder="Enter structure name"></label><label>Source<select id="sourceChoice"><option>Manual Setup</option><option>Connect to Estimate</option></select></label><label>Select # of levels<select id="levelChoice">'+opts(['1','2','3'],String(manualLevels))+'</select></label></div><div class="guidance">Add SOV items as parent rows, then add nested subitems according to the selected number of levels. SOV items are required; descriptions and budgets are optional.</div><div class="manual-table-wrap"><table class="form-table manual-table"><thead><tr><th>SOV Items</th><th>Description</th><th>Budget</th><th>Actions</th></tr></thead><tbody>'+manualTable()+'</tbody></table></div><div class="manual-actions"><button class="btn" id="addSov">＋ Add SOV</button><button class="btn primary" id="save">Save structure</button><button class="btn" id="saveAs">Save with new name</button><button class="btn primary" id="generate">Generate Cashflow Forecast</button><button class="btn" id="excel">Export Excel</button><button class="btn" id="pdf">Export PDF</button></div><div class="saved-structure-preview"><h3>Structure preview</h3><p class="copy">Readonly preview of the hierarchy that will be used for forecast generation.</p><div class="saved-tree">'+manualRows.map(r=>'<div class="manual-node-row '+(r.level>1?'child-row':'parent-row')+'"><span>'+(r.level>1?'↳':'▾')+'</span><b>'+esc(r.sov||'Untitled SOV item')+'</b><span>'+esc(r.description||'')+'</span><strong>'+money(r.budget)+'</strong></div>').join('')+'</div></div></div></section>';
    document.getElementById('sourceChoice').onchange=e=>e.target.value==='Connect to Estimate'?renderEstimate():renderManual();
    document.getElementById('levelChoice').onchange=e=>{manualLevels=Number(e.target.value);manualRows=manualRows.filter(r=>r.level<=manualLevels);renderManual();};
    document.getElementById('addSov').onclick=()=>{manualRows.push({id:'m'+nextId++,parent:null,level:1,sov:'',description:'',budget:0});renderManual();};
    content.querySelectorAll('[data-mf]').forEach(input=>input.oninput=()=>{const r=manualRows.find(x=>x.id===input.closest('[data-mrow]').dataset.mrow);r[input.dataset.mf]=input.dataset.mf==='budget'?Number(input.value||0):input.value;});
    content.querySelectorAll('[data-mdelete]').forEach(b=>b.onclick=()=>{const r=manualRows.find(x=>x.id===b.dataset.mdelete);if(r.level===1&&manualRows.some(x=>x.parent===r.id)&&!confirm('Deleting this parent will also delete its child items. Continue?'))return;manualRows=manualRows.filter(x=>x.id!==r.id&&x.parent!==r.id);renderManual();});
    content.querySelectorAll('.add-sub').forEach(b=>b.onclick=()=>{const parent=manualRows.find(r=>r.id===b.dataset.parent);manualRows.push({id:'m'+nextId++,parent:parent.id,level:parent.level+1,sov:'',description:'',budget:0});renderManual();});
    ['save','saveAs','excel','pdf'].forEach(id=>document.getElementById(id).onclick=()=>alert(id==='excel'?'Excel export prepared.':id==='pdf'?'PDF export prepared.':id==='saveAs'?'Save with new name is ready.':'Bill code structure saved.'));document.getElementById('generate').onclick=()=>{saveBillCode('Manual Setup',manualRows,manualLevels,[]);location.href='forecast.html';};
  }
  function estimateTree(){
    const root={};estimateRows.forEach(r=>{let n=root;estimateGroups.forEach(g=>{const v=r.values[g]||'Unassigned';n[v] ||= {value:v,rows:[],children:{}};n[v].rows.push(r);n=n[v].children;});});
    const walk=(nodes,depth,path)=>Object.values(nodes).map(item=>{const id=path+item.value,has=Object.keys(item.children).length>0,expanded=estimateOpen[id]!==false,total=item.rows.reduce((a,r)=>a+r.budget,0);let h='<div class="estimate-hierarchy-row estimate-level-'+depth+'"><button class="estimate-toggle" data-toggle="'+esc(id)+'" '+(has?'':'disabled')+'>'+(has?(expanded?'▾':'▸'):'•')+'</button><strong>'+esc(item.value)+'</strong><span>'+esc(estimateGroups[depth-1])+'</span><b>'+money(total)+'</b></div>';if(expanded)h+=has?walk(item.children,depth+1,id+'|'):item.rows.map(r=>'<div class="estimate-detail-row"><span>↳</span><input data-erow="'+r.id+'" data-ef="sov" value="'+esc(r.sov)+'"><input data-erow="'+r.id+'" data-ef="description" value="'+esc(r.description)+'" placeholder="Description (optional)"><input data-erow="'+r.id+'" data-ef="budget" type="number" value="'+r.budget+'"><button class="row-delete" data-edel="'+r.id+'">×</button></div>').join('');return h;}).join('');
    return walk(root,1,'');
  }
  function renderEstimate(){
    const e=estimates[0];content.innerHTML='<section class="section"><div class="head"><div><p class="eyebrow">Bill Code Setup · Shockwave</p><h2>Connect to Estimate</h2><p class="copy">Select up to three estimate dimensions. Group 1 is the parent, Group 2 is nested beneath it, and Group 3 is the lowest grouping.</p></div><button class="btn ediphi-button">EDIPHI ↗</button></div><div class="body"><div class="estimate-picker">Estimates<select id="estimateChoice">'+estimates.map((x,i)=>'<option value="'+i+'">'+esc(x[0])+'</option>').join('')+'</select></div><div class="estimate-kpis"><div><small>Total Cost</small><strong>'+money(e[1])+'</strong><span>Across all categories</span></div><div><small>Cost / GSF</small><strong>$'+e[2].toLocaleString(undefined,{minimumFractionDigits:2})+'</strong><span>Current estimate rate</span></div></div><div class="estimate-group-controls"><div><h3>Choose up to 3 grouping levels</h3><p class="copy">Selected groups become parent, subgroup, and lowest-level rollups.</p></div>'+estimateGroups.map((g,i)=>'<label>Group '+(i+1)+'<select data-egroup="'+i+'">'+opts(groups,g)+'</select></label>').join('')+'</div><div class="estimate-hierarchy"><div class="estimate-hierarchy-head"><span>Group / SOV Item</span><span>Level</span><span>Budget</span><span>Actions</span></div>'+estimateTree()+'<div class="estimate-grid-footer"><button class="btn" id="addEstimate">＋ Add SOV</button><strong>Total Budget: '+money(estimateRows.reduce((a,r)=>a+r.budget,0))+'</strong></div></div></div></section>';
    const sourceControls=document.createElement('div');sourceControls.className='bill-toolbar-manual';sourceControls.innerHTML='<label>Bill Code Structure Name<input value="Owner Bill Structure" placeholder="Enter structure name"></label><label>Source<select id="sourceChoice"><option>Manual Setup</option><option selected>Connect to Estimate</option></select></label>';content.querySelector('.body').prepend(sourceControls);document.getElementById('sourceChoice').onchange=e=>e.target.value==='Manual Setup'?renderManual():renderEstimate();
    content.querySelectorAll('.estimate-detail-row').forEach((row,i)=>{const r=estimateRows.find(x=>x.id===Number(row.querySelector('[data-erow]')?.dataset.erow))||estimateRows[i];row.innerHTML='<span>↳ '+esc(r.sov)+'</span><span>'+esc(r.description)+'</span><b>'+money(r.budget)+'</b>';});content.querySelector('#addEstimate')?.remove();const estimateActions=document.createElement('div');estimateActions.className='manual-actions';estimateActions.innerHTML='<button class="btn primary" id="saveEstimate">Save structure</button><button class="btn" id="saveEstimateAs">Save with new name</button><button class="btn primary" id="generateEstimate">Generate Cashflow Forecast</button><button class="btn" id="exportEstimate">Export Excel</button><button class="btn" id="exportEstimatePdf">Export PDF</button>';content.querySelector('.body').append(estimateActions);
    document.getElementById('saveEstimate').onclick=()=>alert('Estimate bill code structure saved.');document.getElementById('saveEstimateAs').onclick=()=>alert('Save with new name is ready.');document.getElementById('generateEstimate').onclick=()=>{saveBillCode('Connect to Estimate',estimateRows,estimateGroups.length,estimateGroups);location.href='forecast.html';};document.getElementById('exportEstimate').onclick=()=>alert('Excel export prepared.');document.getElementById('exportEstimatePdf').onclick=()=>alert('PDF export prepared.');
    document.getElementById('estimateChoice').onchange=e=>{const x=estimates[Number(e.target.value)];content.querySelector('.estimate-kpis').innerHTML='<div><small>Total Cost</small><strong>'+money(x[1])+'</strong><span>Across all categories</span></div><div><small>Cost / GSF</small><strong>$'+x[2].toLocaleString(undefined,{minimumFractionDigits:2})+'</strong><span>Current estimate rate</span></div>';};
    const hierarchy=content.querySelector('.estimate-hierarchy');const chipbar=document.createElement('div');chipbar.className='estimate-group-chips';chipbar.innerHTML=estimateGroups.map((g,i)=>'<span class="estimate-group-chip"><b>⠿</b>'+esc(g)+'<button data-remove-group="'+i+'">×</button></span>'+ (i<estimateGroups.length-1?'<span class="estimate-chip-arrow">›</span>':'')).join('');hierarchy.prepend(chipbar);const header=hierarchy.querySelector('.estimate-hierarchy-head');header.children[0].textContent='Order';header.children[1].textContent='Description';header.children[2].textContent='Total';header.children[3].textContent='Actions';
    document.querySelectorAll('[data-remove-group]').forEach(b=>b.onclick=()=>{if(estimateGroups.length<=1)return;estimateGroups.splice(Number(b.dataset.removeGroup),1);while(estimateGroups.length<3)estimateGroups.push(groups[estimateGroups.length]);estimateOpen={};renderEstimate();});
    document.querySelectorAll('[data-egroup]').forEach(s=>s.onchange=()=>{const i=Number(s.dataset.egroup);if(estimateGroups.some((g,j)=>j!==i&&g===s.value)){s.value=estimateGroups[i];return;}estimateGroups[i]=s.value;estimateOpen={};renderEstimate();});
    document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{estimateOpen[b.dataset.toggle]=estimateOpen[b.dataset.toggle]===false;renderEstimate();});
  }
  renderEstimate();
})();
