(function(){
  const key='hubCashflowState',state=JSON.parse(localStorage.getItem(key)||'{}');
  const nav=[['index.html','Lifecycle Overview','▣'],['prediction.html','Early Cashflow Prediction','◈'],['manual-forecast.html','Manual Forecast Setup','⌘'],['wbs.html','Work Breakdown Structure Setup','⌘'],['bill-code.html','Bill Code Setup','⌗'],['billing.html','Estimate Billing Structure','＋'],['forecast.html','Cashflow Forecast Grid','▤']];
  const connectedTags='<span class="connected">✓ Cosential · connected</span><span class="connected">✓ Ediphi · connected</span>'+(state.wbsSchedule?'<span class="connected">✓ P6 · connected</span>':'');
  document.body.innerHTML='<div class="topbar"><b>▦</b><b>▣ Projects</b><span>▤ Enterprise Workspace</span></div><div class="projectbar"><span class="logo">HUB</span><span>›</span><strong>D3-R25006-00 - META RPI HAC</strong><span>›</span><strong>CASHFLOW FORECASTING</strong><span class="right">♙ ♧ ? ▣ RC</span></div><div class="shell"><aside><a class="back" href="index.html">← Back to Home</a><h3>Cashflow lifecycle</h3>'+nav.map(n=>'<a href="'+n[0]+'" class="'+(n[1]==='Cashflow Forecast Grid'?'active':'')+'"><span class="phase"><i>'+n[2]+'</i>'+n[1]+'</span></a>').join('')+'<h3>Workspace</h3><a href="modules/reports.html">▧ Reports</a><a href="modules/settings.html">⚙ Project Settings</a></aside><main class="main"><div class="source-strip">'+connectedTags+'<span>Last refresh · Today, 9:42 AM</span></div><div id="content"></div></main></div>';
  const content=document.getElementById('content'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>'$'+Math.round(Number(n)||0).toLocaleString(),compact=n=>{n=Math.abs(Number(n)||0);return n>=1000000?'$'+(n/1000000).toFixed(1)+'M':n>=1000?'$'+Math.round(n/1000)+'K':'$'+Math.round(n)},parseBudget=v=>Number(String(v??0).replace(/[$,]/g,''))||0,dateOnly=v=>v?new Date(v+'T00:00:00'):null,monthKey=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'),monthLabel=d=>d.toLocaleDateString('en-US',{month:'short',year:'2-digit'}).toUpperCase();
  const monthsBetween=(start,end)=>{const out=[],d=new Date(start.getFullYear(),start.getMonth(),1),last=new Date(end.getFullYear(),end.getMonth(),1);while(d<=last){out.push({key:monthKey(d),label:monthLabel(d),date:new Date(d)});d.setMonth(d.getMonth()+1)}return out};
  const fallback=[['01','Demolition',[['01.50','Temporary ICRA Barriers and Infection Control','325,090']]],['02','Sitework',[['02.45','Selective Site and Building Demolition','79,975']]],['03','Foundations',[['03.30','Cast-In-Place Concrete (Turnkey)','20,000']]],['04','Substructure',[]],['05','Superstructure',[['05.00','Structural Steel (Turnkey)','30,000']]],['06','Exterior Skin',[['06.41','Architectural Wood Casework','75,370']]],['07','Roofing',[['07.50','Roofing','10,000']]],['08','Interior Construction',[]],['09','Conveying Systems',[]],['10','Equipment / Special Construction',[]],['11','Plumbing',[]],['12','Fire Protection',[]],['13','HVAC',[]],['14','Electrical',[]],['15','Jobsite Management',[]],['16','Site Requirements',[]],['17','Preconstruction',[]],['18','Special Contingencies',[]],['19','Fee',[]],['20','Change Quotations',[]],['99','Other',[]]];
  const systems=(state.wbsSystems&&state.wbsSystems.length?state.wbsSystems:fallback).map(s=>[s[0],s[1],(s[2]||[]).map(c=>[c[0],c[1],c[2],c[3]])]),schedule=state.wbsScheduleData||{},curves=state.wbsLineCurves||{},curveFor=c=>curves[c]||'Flat',dateText=d=>{const date=d instanceof Date?d:new Date(d+'T00:00:00');return String(date.getMonth()+1).padStart(2,'0')+'/'+String(date.getDate()).padStart(2,'0')+'/'+date.getFullYear()};
  const weights=(curve,n)=>{if(n<2)return [1];if(curve==='Front-loaded')return Array.from({length:n},(_,i)=>n-i);if(curve==='Back-loaded')return Array.from({length:n},(_,i)=>i+1);if(curve==='Bell')return Array.from({length:n},(_,i)=>1+Math.min(i,n-1-i));return Array(n).fill(1)};
  function model(){const dates=Object.values(schedule).map(v=>[dateOnly(v.start),dateOnly(v.end)]).flat().filter(Boolean),start=dates.length?new Date(Math.min(...dates.map(d=>d.getTime()))):new Date(2026,0,1),end=dates.length?new Date(Math.max(...dates.map(d=>d.getTime()))):new Date(2026,10,30),months=monthsBetween(start,end),index=Object.fromEntries(months.map((m,i)=>[m.key,i])),children=[];systems.forEach((s,pi)=>s[2].forEach((c,ci)=>{const info=schedule[c[0]]||schedule[s[0]]||{},a=dateOnly(info.start)||start,b=dateOnly(info.end)||end,first=Math.max(0,index[monthKey(new Date(a.getFullYear(),a.getMonth(),1))]??0),last=Math.min(months.length-1,index[monthKey(new Date(b.getFullYear(),b.getMonth(),1))]??months.length-1),count=Math.max(1,last-first+1),ws=weights(curveFor(c[0]),count),total=ws.reduce((x,y)=>x+y,0),budget=parseBudget(c[2]),forecast=months.map((_,i)=>i>=first&&i<=last?budget*ws[i-first]/total:0);children.push({pi,ci,code:c[0],name:c[1],budget,forecast,start:a,end:b,curve:curveFor(c[0])})}));const cutoff=new Date();cutoff.setDate(1),actual=children.map((r,ri)=>r.forecast.map((v,i)=>months[i].date>cutoff?null:v*(.84+((ri*7+i*3)%17)/100))),forecastTotal=children.reduce((s,r)=>s+r.budget,0),actualToDate=actual.reduce((s,r)=>s+r.reduce((a,v)=>a+(v||0),0),0),forecastToDate=children.reduce((s,r)=>s+r.forecast.reduce((a,v,i)=>a+(months[i].date<=cutoff?v:0),0),0);return{months,children,actual,forecastTotal,actualToDate,variance:forecastToDate-actualToDate,cutoff}};
  function chart(m){const w=1000,h=290,p={l:58,r:20,t:18,b:34},n=m.months.length||1,fc=m.months.map((_,i)=>m.children.reduce((s,r)=>s+r.forecast[i],0)),ac=m.months.map((_,i)=>m.actual.reduce((s,r)=>s+(r[i]||0),0));let f=0,a=0;const fp=fc.map(v=>f+=v),ap=ac.map(v=>a+=v),max=Math.max(...fp,1),x=i=>p.l+i*(w-p.l-p.r)/Math.max(1,n-1),y=v=>h-p.b-v/max*(h-p.t-p.b),points=a=>a.map((v,i)=>x(i)+','+y(v)).join(' '),grid=[0,.25,.5,.75,1].map(q=>'<line x1="'+p.l+'" y1="'+y(max*q)+'" x2="'+(w-p.r)+'" y2="'+y(max*q)+'"/><text x="8" y="'+(y(max*q)+4)+'">'+compact(max*q)+'</text>').join('');return'<div class="cashflow-chart"><svg viewBox="0 0 '+w+' '+h+'"><g class="cf-grid-lines">'+grid+'</g><polygon class="cf-forecast-area" points="'+points(fp)+' '+x(n-1)+','+(h-p.b)+' '+x(0)+','+(h-p.b)+'"/><polyline class="cf-forecast-line" points="'+points(fp)+'"/><polyline class="cf-actual-line" points="'+points(ap)+'"/>'+m.months.map((z,i)=>'<text class="cf-x-label" x="'+x(i)+'" y="'+(h-8)+'">'+z.label+'</text>').join('')+'</svg><div class="cf-legend"><span><i class="cf-key-forecast"></i>Forecast</span><span><i class="cf-key-actual"></i>Actuals to date</span></div></div>'}
  function render(){const m=model(),parents=systems.map((s,pi)=>{const lines=m.children.filter(r=>r.pi===pi);return{pi,s,lines,values:m.months.map((_,i)=>lines.reduce((x,r)=>x+r.forecast[i],0))}}),open=Object.fromEntries(parents.map(p=>[p.pi,true])),totals=m.months.map((_,i)=>m.children.reduce((s,r)=>s+r.forecast[i],0)),tone=p=>['blue','lavender','sage','peach','sand'][p%5],firstForecast=m.months.findIndex(z=>z.date>m.cutoff),monthTone=i=>(m.months[i].date<=m.cutoff?'cf-month-past':'cf-month-future')+(i===firstForecast?' cf-forecast-boundary':''),activeTone=(start,end,i,color)=>{const month=m.months[i].date,from=new Date(start.getFullYear(),start.getMonth(),1),to=new Date(end.getFullYear(),end.getMonth(),1);return month>=from&&month<=to?' cf-active-'+color:''},detailCells=(start,end,curve)=>'<td class="cf-detail-col">'+dateText(start)+'</td><td class="cf-detail-col">'+dateText(end)+'</td><td class="cf-detail-col">'+esc(curve)+'</td>';const rows=()=>parents.map(p=>{const start=p.lines.length?new Date(Math.min(...p.lines.map(r=>r.start.getTime()))):new Date(2026,0,1),end=p.lines.length?new Date(Math.max(...p.lines.map(r=>r.end.getTime()))):new Date(2026,10,30);return'<tr class="cf-parent"><td><button class="cf-toggle" data-parent="'+p.pi+'">'+(open[p.pi]?'▾':'▸')+'</button><b>'+esc(p.s[0])+' · '+esc(p.s[1])+'</b></td>'+detailCells(start,end,'—')+p.values.map((v,i)=>'<td class="'+monthTone(i)+activeTone(start,end,i,tone(p.pi))+'">'+money(v)+'</td>').join('')+'<td class="cf-total">'+compact(p.values.reduce((a,b)=>a+b,0))+'</td></tr>'+(open[p.pi]?p.lines.map(r=>{const ri=m.children.indexOf(r);return'<tr class="cf-child"><td>↳ '+esc(r.code)+' · '+esc(r.name)+'</td>'+detailCells(r.start,r.end,r.curve)+r.forecast.map((v,i)=>{const a=m.actual[ri][i],tip=a===null?'Forecast: '+money(v)+' · Future month':'Forecast: '+money(v)+' · Actual: '+money(a)+' · Variance: '+(v-a>=0?'+':'−')+money(Math.abs(v-a));return'<td class="cf-cell '+(a===null?'future':'past')+' '+monthTone(i)+activeTone(r.start,r.end,i,tone(p.pi))+'" data-tooltip="'+esc(tip)+'">'+(v?money(v):'—')+'</td>'}).join('')+'<td class="cf-total">'+compact(r.budget)+'</td></tr>'}).join(''):'')}).join('');
    const totalRow='<tr class="cf-month-total"><td><b>Monthly total</b></td><td class="cf-detail-col"></td><td class="cf-detail-col"></td><td class="cf-detail-col"></td>'+totals.map((v,i)=>'<td class="'+monthTone(i)+'"><b>'+compact(v)+'</b></td>').join('')+'<td><b>'+compact(m.forecastTotal)+'</b></td></tr>';
    content.innerHTML='<section class="section"><div class="head forecast-header"><div><p class="eyebrow">Phase 4 · Forecast vs actuals</p><h2>Cashflow Forecast</h2><p class="copy">Generated from <b>'+esc(state.source||'Work Breakdown Structure Setup')+'</b>. Forecast values use WBS budgets, schedule dates, and selected curves.</p></div><div class="actions"><span class="pill good">WBS connected</span><a class="btn" href="wbs.html">Back to WBS setup</a></div></div><div class="body"><div class="metrics cf-metrics"><div class="metric"><small>Total Forecast</small><strong>'+compact(m.forecastTotal)+'</strong></div><div class="metric"><small>Actuals to Date</small><strong>'+compact(m.actualToDate)+'</strong></div><div class="metric"><small>Variance</small><strong class="'+(m.variance>=0?'variance':'cf-negative')+'">'+(m.variance>=0?'+':'−')+compact(m.variance)+'</strong></div></div><div class="cf-panel"><h3>Cumulative cashflow</h3><p class="copy">Forecast curve with simulated actuals to date.</p>'+chart(m)+'</div><div class="cf-panel cf-grid-panel"><div class="cf-panel-head"><div><h3>Monthly planning grid</h3><p class="copy">Forecast by DPR system and cost code. Hover a past-month cell to compare Actual and Variance.</p></div><div class="actions"><span class="pill">'+m.months.length+' months · '+(state.wbsGroup||'WBS mapped')+'</span><button class="btn" id="toggleDetails">Show details</button></div></div><div class="cf-table-wrap"><table class="cf-table"><thead><tr><th>Billing code</th><th class="cf-detail-col">Start date</th><th class="cf-detail-col">End date</th><th class="cf-detail-col">Distribution curve</th>'+m.months.map((z,i)=>'<th class="'+monthTone(i)+'">'+z.label+'</th>').join('')+'<th>Total</th></tr></thead><tbody>'+rows()+totalRow+'</tbody></table></div><div class="cf-tooltip" id="cfTooltip"></div></div><div class="guidance">Hover over any past-month cost-code cell to compare its simulated actual with the forecast and see the variance. Parent rows roll up their child cost codes.</div></div></section>';
    const bind=()=>{content.querySelectorAll('.cf-toggle').forEach(b=>b.onclick=()=>{open[Number(b.dataset.parent)]=!open[Number(b.dataset.parent)];content.querySelector('.cf-table tbody').innerHTML=rows()+totalRow;bind()});const detailButton=document.getElementById('toggleDetails');if(detailButton)detailButton.onclick=()=>{const panel=document.querySelector('.cf-grid-panel');panel.classList.toggle('show-details');detailButton.textContent=panel.classList.contains('show-details')?'Hide details':'Show details'};const tip=document.getElementById('cfTooltip');content.querySelectorAll('.cf-cell').forEach(c=>{c.onmouseenter=()=>{tip.textContent=c.dataset.tooltip;tip.classList.add('visible');const b=c.getBoundingClientRect(),p=tip.parentElement.getBoundingClientRect();tip.style.left=(b.left-p.left+b.width/2)+'px';tip.style.top=(b.top-p.top-8)+'px'};c.onmouseleave=()=>tip.classList.remove('visible')})};bind()}
  let billTier=(JSON.parse(localStorage.getItem('hubBillCodeStructure')||'null')||{}).groups?.length||Number((JSON.parse(localStorage.getItem('hubBillCodeStructure')||'null')||{}).levels)||1;const billOpen={};
  const renderBillCodeTable=()=>{
    const saved=JSON.parse(localStorage.getItem('hubBillCodeStructure')||'null');
    if(!saved)return;
    const panel=document.querySelector('.cf-grid-panel');if(!panel)return;
    const groups=saved.groups||[], maxTier=Math.max(1,groups.length||Number(saved.levels)||1), rows=saved.rows||[], overrides=JSON.parse(localStorage.getItem('hubForecastOverrides')||'{}'), isEstimate=String(saved.source||'').toLowerCase().includes('estimate')||groups.length>0;
    const estimateBudgets=[4000,23000,1716,2220,12057,3285,6830,3498,3500,16830,3440,3585,27250,90957,36263,22432,26669,159494,39040,22320,159363,42000,5000,121977,85710,187472,373880,37500,1380,7680,7400,417068,87500,46839], estimateCodes=['015219.1200','015219.1200','010000.9816','010000.9817','010000.9815','010000.9840','020000.0245','024119.9950','028000.1100','033000.1150','033000.9900','033000.9900','030000.1320','055000.9900','061000.3340','075113.7100','080000.0805','090000.0920','090000.0950','090000.0990','140000.1410','210000.0000','210000.0001','220000.1008','226213.C110','230000.1100','260002.1050','270000.1010','013150.3610','013150.3110','013150.1310','010000.2100','017413.2100','010000.3100'], estimateDescriptions=['Temporary Toilet Trailer Mob./Demob.','Temporary Toilets Monthly Rental','Monthly Rental','Plywood Enclosure','Scaffold Stair for Safe Access','Final Cleaning','Demo Slab on Grade at New Footing','Scanning / Utility Locating','Hazardous Materials Survey','Concrete Spread Footing','Excavate Spread Footing','Soil Testing for Off-Haul','CONC-1,2 & Rubber Base','Mezzanine Posts & Rail, D/B Stair','Roof Joists & Leveling Curbs','Roofing Patch - Misc Repair','Hollow Metal DFH with 1/4" Glass','Interior Framing & Drywall','ACT 2x2 Square USG Olympia in 9/16" Grid','Interior Paint','VRC Series D Material Lift','Fire Sprinkler Adjustments','Relocate (E) Piping Allowance','Lab Sink Fixtures, Piping & Rough-In','CDA, Argon, O2 Systems','Mechanical System','Lighting, Branch & Equipment Power','Low Voltage Cabling & Terminations','Estimating Assistant (Precon)','Estimator/Project Buy-out (Precon)','Project Manager (Precon)','Jobsite Management','Interim Clean Up & Safety Labor','Project Requirements'];
    const date=(i)=>{const d=new Date(2026, i%12, 5);return d}, end=(i)=>{const d=new Date(2026, (i%12)+((i%4)+1), 0);return d};
    const fmt=d=>d.toLocaleDateString('en-US',{month:'2-digit',day:'2-digit',year:'numeric'}), months=(a,b)=>Math.max(1,(b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth()+1);
    const forecastMonths=model().months, cells=(info,tone,depth)=>forecastMonths.map(z=>{const active=z.date>=new Date(info.start.getFullYear(),info.start.getMonth(),1)&&z.date<=new Date(info.finish.getFullYear(),info.finish.getMonth(),1);return '<td class="'+(active?'cf-duration-cell cf-duration-tone-'+tone+' cf-duration-tier-'+Math.min(depth,3):'')+'">'+ (active?money(info.budget/months(info.start,info.finish)):'—')+'</td>'}).join('');
    const curve=(r,i)=>r.curve||r.distributionCurve||['Flat','Front-loaded','Bell','Back-loaded'][i%4], prefix=code=>String(code||'').slice(0,2), fallbackGroups={System:{'01':'Jobsite Management','02':'Demolition','03':'Foundations','05':'Superstructure','06':'Exterior Skin','07':'Exterior Skin','08':'Interior Construction','09':'Interior Construction','14':'Electrical','21':'Fire Protection','22':'Plumbing','23':'HVAC','26':'Electrical','27':'Conveying Systems'},UF1:{'01':'Z - General','02':'F - Special Construction and Demolition','03':'A - Substructure','05':'B - Shell','06':'B - Shell','07':'B - Shell','08':'C - Interiors','09':'C - Interiors','14':'D - Services','21':'D - Services','22':'D - Services','23':'D - Services','26':'D - Services','27':'D - Services'},'Bid Package':{'01':'01.25 - Temporary Sanitary Facilities','02':'02.45 - Demolition','03':'03.30 - Concrete','05':'05.50 - Metal Fabrications','06':'06.10 - Rough Carpentry','07':'07.50 - Roofing','08':'08.10 - Doors and Frames','09':'09.21 - Finishes','14':'14.10 - Dumbwaiters','21':'21.00 - Fire Suppression','22':'22.00 - Plumbing','23':'23.00 - HVAC','26':'26.00 - Electrical','27':'27.10 - Structured Cabling'}}, valueFor=(r,g,i)=>(r.values&&r.values[g])||((fallbackGroups[g]||{})[prefix(r.order||r.sov)])||'Unassigned', iso=d=>d.toISOString().slice(0,10), applyOverride=(id,info)=>{const o=overrides[id]||{};return Object.assign({},info,{start:o.start?new Date(o.start):info.start,finish:o.finish?new Date(o.finish):info.finish,curve:o.curve||info.curve})};
    const tree={};
    const node=(parent,key,label,level)=>{parent[key] ||= {key,label,level,children:{},lines:[]};return parent[key]};
    const sourceRows=isEstimate?rows.map((r,i)=>Object.assign({},r,{order:r.order||r.sov||estimateCodes[i%estimateCodes.length],description:r.description||r.lineDescription||estimateDescriptions[i%estimateDescriptions.length],budget:Number(r.budget)||estimateBudgets[i%estimateBudgets.length]})):rows;
    if(isEstimate)sourceRows.forEach((r,i)=>{let n=tree,leaf;(groups.length?groups:[]).forEach((g,gi)=>{const value=valueFor(r,g,i),child=node(n,value,value,gi+1);leaf=child;n=child.children;});(leaf.lines||=[]).push({code:r.order||r.sov||('SOV '+(i+1)),description:r.description||r.lineDescription||'',budget:Number(r.budget)||estimateBudgets[i%estimateBudgets.length],start:date(i),finish:end(i),curve:curve(r,i)});});
    else rows.filter(r=>!r.parent).forEach((r,i)=>{const walk=(r,n)=>{const x=node(n,r.id,r.sov||'Untitled SOV item',Number(r.level)||1);x.lines.push({code:'',description:r.description||'',budget:Number(r.budget)||0,start:date(i),finish:end(i),curve:curve(r,i)});rows.filter(c=>c.parent===r.id).forEach(c=>walk(c,x.children));};walk(r,tree);});
    const normalize=(nodes)=>Object.values(nodes).forEach(n=>{if(n.__lines){n.lines=(n.lines||[]).concat(n.__lines);delete n.__lines}normalize(n.children||{})});normalize(tree);
    const roll=(n)=>{const children=Object.values(n.children||{}),own=children.length?[]:(n.lines||[]),items=own.concat(...children.map(roll).map(x=>x.items));return{items,start:items.length?new Date(Math.min(...items.map(x=>x.start))):date(0),finish:items.length?new Date(Math.max(...items.map(x=>x.finish))):end(0),budget:items.reduce((s,x)=>s+x.budget,0),curve:items.length&&items.every(x=>x.curve===items[0].curve)?items[0].curve:'Mixed'};};
    const editCells=(id,info,depth,tone)=>depth===billTier?'<td><input class="cf-date-edit" data-fedit="start" data-bill-id="'+id+'" type="date" value="'+iso(info.start)+'"></td><td><input class="cf-date-edit" data-fedit="finish" data-bill-id="'+id+'" type="date" value="'+iso(info.finish)+'"></td><td>'+months(info.start,info.finish)+' mo</td><td><select class="cf-curve-edit" data-fedit="curve" data-bill-id="'+id+'"><option '+(info.curve==='Flat'?'selected':'')+'>Flat</option><option '+(info.curve==='Front-loaded'?'selected':'')+'>Front-loaded</option><option '+(info.curve==='Back-loaded'?'selected':'')+'>Back-loaded</option><option '+(info.curve==='Bell'?'selected':'')+'>Bell</option></select></td>'+cells(info,tone,depth):'<td>'+fmt(info.start)+'</td><td>'+fmt(info.finish)+'</td><td>'+months(info.start,info.finish)+' mo</td><td>'+esc(info.curve)+'</td>'+cells(info,tone,depth);
    const line=(label,info,depth,leaf=false,tone=0)=>'<tr class="cf-bill-row cf-bill-level-'+depth+' cf-bill-tone-'+tone+' '+(leaf?'cf-bill-leaf':'cf-bill-group')+'"><td><span class="cf-bill-indent">'+(leaf?'↳':'')+'</span><b>'+esc(label)+'</b></td><td>'+esc(info.description||'')+'</td><td>'+compact(info.budget)+'</td>'+editCells('',info,depth,tone)+'</tr>';
    const walk=(nodes,path,depth,toneIndex=0)=>Object.values(nodes).filter(n=>n.key!=='__lines').map((n,i)=>{const id=path+i,tone=depth===1?i%5:toneIndex,info=applyOverride(id,roll(n)),expanded=billOpen[id]!==false;let h='<tr class="cf-bill-row cf-bill-level-'+depth+' cf-bill-tone-'+tone+'"><td><button class="cf-bill-toggle" data-bill-id="'+id+'">'+(expanded?'▾':'▸')+'</button><b>'+esc(n.label)+'</b></td><td>'+esc(groups[depth-1]||'')+'</td><td>'+compact(info.budget)+'</td>'+editCells(id,info,depth,tone)+'</tr>';if(expanded){if(depth<billTier)h+=walk(n.children,id+'-',depth+1,tone);if(depth===billTier){const leaves=n.__lines||info.items.filter(x=>x.code||!Object.keys(n.children||{}).length);leaves.forEach(x=>h+=line(x.code||x.description,x,depth+1,true,tone));}}return h;}).join('');
    const total=Object.values(tree).reduce((s,n)=>s+roll(n).budget,0);
    panel.querySelector('.cf-panel-head').innerHTML='<div><h3>Monthly planning grid</h3><p class="copy">Read-only forecast by Bill Code Structure. Duration and curve roll up from the selected tier.</p></div><div class="actions"><label class="forecast-tier-control">Forecast at <select id="forecastTier">'+Array.from({length:maxTier},(_,i)=>'<option value="'+(i+1)+'" '+(billTier===i+1?'selected':'')+'>Tier '+(i+1)+(groups[i]?' · '+esc(groups[i]):'')+'</option>').join('')+'</select></label></div>';
    panel.querySelector('.cf-table-wrap').innerHTML='<table class="cf-table cf-bill-table"><thead><tr><th>Group / SOV item</th><th>Description / tier</th><th>Budget</th><th>Start date</th><th>End date</th><th>Duration</th><th>Distribution curve</th>'+forecastMonths.map(z=>'<th>'+z.label+'</th>').join('')+'</tr></thead><tbody>'+walk(tree,'',1)+'<tr class="cf-month-total"><td colspan="2"><b>Grand total</b></td><td><b>'+compact(total)+'</b></td><td colspan="5"></td>'+forecastMonths.map(z=>'<td><b>—</b></td>').join('')+'</tr></tbody></table>';
    panel.querySelector('#forecastTier').onchange=e=>{billTier=Number(e.target.value);renderBillCodeTable()};panel.querySelectorAll('.cf-bill-toggle').forEach(b=>b.onclick=()=>{billOpen[b.dataset.billId]=billOpen[b.dataset.billId]===false;renderBillCodeTable()});panel.querySelectorAll('[data-fedit]').forEach(input=>input.onchange=e=>{const id=input.dataset.billId;overrides[id]=Object.assign({},overrides[id],{[input.dataset.fedit]:input.value});localStorage.setItem('hubForecastOverrides',JSON.stringify(overrides));renderBillCodeTable()});
  };
  render();
  renderBillCodeTable();
  const scheduleControl=document.createElement('label');
  scheduleControl.className='forecast-schedule-control';
  scheduleControl.innerHTML='<span>Connect to schedule</span><select aria-label="Connect to schedule"><option value="">Select a P6 schedule</option><option>P6 Baseline v12 · 08/20/2026</option><option>P6 Update 03 · 09/05/2026</option><option>P6 Recovery Plan · 09/12/2026</option></select>';
  document.querySelector('.forecast-header .actions')?.prepend(scheduleControl);
  scheduleControl.querySelector('select').onchange=e=>{if(e.target.value){state.wbsSchedule=e.target.value;localStorage.setItem(key,JSON.stringify(state));scheduleControl.querySelector('span').textContent='Schedule connected';}};
  const forecastActions=document.querySelector('.forecast-header .actions');
  const setupLink=document.querySelector('.forecast-header a[href="wbs.html"]');if(setupLink){setupLink.textContent='Bill Code Setup';setupLink.href='bill-code.html'}
  if(forecastActions){const snapshotButton=document.createElement('button');snapshotButton.className='btn primary';snapshotButton.textContent='Save forecast snapshot';snapshotButton.onclick=()=>{state.snapshot='Saved '+new Date().toLocaleString('en-US');state.generated=true;localStorage.setItem(key,JSON.stringify(state));snapshotButton.textContent='Snapshot saved';setTimeout(()=>snapshotButton.textContent='Save forecast snapshot',1800)};const exportButton=document.createElement('button');exportButton.className='btn';exportButton.textContent='Export forecast to Excel';exportButton.onclick=()=>{exportButton.textContent='Excel export ready';setTimeout(()=>exportButton.textContent='Export forecast to Excel',1800)};forecastActions.append(snapshotButton,exportButton)}
  const ownerNavLink=document.createElement('a');ownerNavLink.href='owner-bill-code.html';ownerNavLink.innerHTML='<span class="phase"><i>↔</i>Owner Bill Code Mapping</span>';document.querySelector('aside a[href="bill-code.html"]')?.after(ownerNavLink);
  const projectTextFix=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let projectNode;while(projectNode=projectTextFix.nextNode()){projectNode.nodeValue=projectNode.nodeValue.replaceAll('D3-R25006-00 - META RPI HAC','D0-A25061-00 - SHOCKWAVE - 2026 MISC PROJECTS').replaceAll('D3-R25006-00','D0-A25061-00').replaceAll('Meta RPI HAC','Shockwave - 2026 Misc Projects').replaceAll('META RPI HAC','SHOCKWAVE - 2026 MISC PROJECTS')}
})();
